// <auto-generated />
using HeracleumSosnowskyiService.Data.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeracleumSosnowskyiService.Data.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgreSQLDbContext))]
    [Migration("20231228073232_InitialFileEarthsensing")]
    partial class InitialFileEarthsensing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeracleumSosnowskyiService.Models.EarthRemoteSensingData", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("LandsatProductId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EarthRemoteSensingDates");
                });

            modelBuilder.Entity("HeracleumSosnowskyiService.Models.FileInfoApi", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileStreamId")
                        .HasColumnType("text");

                    b.Property<long>("LastModified")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FileInfo");
                });

            modelBuilder.Entity("HeracleumSosnowskyiService.Models.FileMetadata", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ErsDataId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("FileInfoId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileStreamId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ErsDataId");

                    b.HasIndex("FileInfoId")
                        .IsUnique();

                    b.ToTable("FileMetadates");
                });

            modelBuilder.Entity("HeracleumSosnowskyiService.Models.FileMetadata", b =>
                {
                    b.HasOne("HeracleumSosnowskyiService.Models.EarthRemoteSensingData", "EarthRemoteSensingData")
                        .WithMany("Metadates")
                        .HasForeignKey("ErsDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeracleumSosnowskyiService.Models.FileInfoApi", "FileInfo")
                        .WithOne("Metadata")
                        .HasForeignKey("HeracleumSosnowskyiService.Models.FileMetadata", "FileInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EarthRemoteSensingData");

                    b.Navigation("FileInfo");
                });

            modelBuilder.Entity("HeracleumSosnowskyiService.Models.EarthRemoteSensingData", b =>
                {
                    b.Navigation("Metadates");
                });

            modelBuilder.Entity("HeracleumSosnowskyiService.Models.FileInfoApi", b =>
                {
                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
