// <auto-generated />
using HeracleumSosnowskyiService.Data.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeracleumSosnowskyiService.Data.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgreSQLDbContext))]
    partial class PostgreSQLDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeracleumSosnowskyiService.Models.Datasets", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("FileInfoId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileStreamId")
                        .HasColumnType("text");

                    b.Property<byte[]>("SatelliteDataId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("FileInfoId")
                        .IsUnique();

                    b.HasIndex("SatelliteDataId");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("HeracleumSosnowskyiService.Models.FileInfoApi", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LastModified")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FileInfo");
                });

            modelBuilder.Entity("HeracleumSosnowskyiService.Models.SatelliteDataOfSpacesystem", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("LandsatProductId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SatelliteData");
                });

            modelBuilder.Entity("HeracleumSosnowskyiService.Models.Datasets", b =>
                {
                    b.HasOne("HeracleumSosnowskyiService.Models.FileInfoApi", "FileInfo")
                        .WithOne("Datasets")
                        .HasForeignKey("HeracleumSosnowskyiService.Models.Datasets", "FileInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeracleumSosnowskyiService.Models.SatelliteDataOfSpacesystem", "SatelliteData")
                        .WithMany("Datasets")
                        .HasForeignKey("SatelliteDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileInfo");

                    b.Navigation("SatelliteData");
                });

            modelBuilder.Entity("HeracleumSosnowskyiService.Models.FileInfoApi", b =>
                {
                    b.Navigation("Datasets");
                });

            modelBuilder.Entity("HeracleumSosnowskyiService.Models.SatelliteDataOfSpacesystem", b =>
                {
                    b.Navigation("Datasets");
                });
#pragma warning restore 612, 618
        }
    }
}
