using System.Xml.Serialization;

namespace HeracleumSosnowskyiService.Models.Xml
{
    public class ProductContent
    {
        [XmlElement(ElementName = "ORIGIN")]
        public string? Origin;
        [XmlElement(ElementName = "DIGITAL_OBJECT_IDENTIFIER")]
        public string? DigitalObjectIdentifier;
        [XmlElement(ElementName = "LANDSAT_PRODUCT_ID")]
        public string? LandsatProductId;
        [XmlElement(ElementName = "PROCESSING_LEVEL")]
        public string? ProcessingLevel;
        [XmlElement(ElementName = "COLLECTION_NUMBER")]
        public string? CollectionNumber;
        [XmlElement(ElementName = "COLLECTION_CATEGORY")]
        public string? CollectionCategory;
        [XmlElement(ElementName = "OUTPUT_FORMAT")]
        public string? Output_format;
        [XmlElement(ElementName = "FILE_NAME_BAND_1")]
        public string? FileNameBand1;
        [XmlElement(ElementName = "FILE_NAME_BAND_2")]
        public string? FileNameBand2;
        [XmlElement(ElementName = "FILE_NAME_BAND_3")]
        public string? FileNameBand3;
        [XmlElement(ElementName = "FILE_NAME_BAND_4")]
        public string? FileNameBand4;
        [XmlElement(ElementName = "FILE_NAME_BAND_5")]
        public string? FileNameBand5;
        [XmlElement(ElementName = "FILE_NAME_BAND_6")]
        public string? FileNameBand6;
        [XmlElement(ElementName = "FILE_NAME_BAND_7")]
        public string? FileNameBand7;
        [XmlElement(ElementName = "FILE_NAME_BAND_ST_B10")]
        public string? FileNameBandStB10;
        [XmlElement(ElementName = "FILE_NAME_THERMAL_RADIANCE")]
        public string? FileNameThermalRadiance;
        [XmlElement(ElementName = "FILE_NAME_UPWELL_RADIANCE")]
        public string? FileNameUpwellRadiance;
        [XmlElement(ElementName = "FILE_NAME_DOWNWELL_RADIANCE")]
        public string? FileNameDownwellRadiance;
        [XmlElement(ElementName = "FILE_NAME_ATMOSPHERIC_TRANSMITTANCE")]
        public string? FileNameAtmosphericTransmittance;
        [XmlElement(ElementName = "FILE_NAME_EMISSIVITY")]
        public string? FileNameEmissivity;
        [XmlElement(ElementName = "FILE_NAME_EMISSIVITY_STDEV")]
        public string? FileNameEmissivityStdev;
        [XmlElement(ElementName = "FILE_NAME_CLOUD_DISTANCE")]
        public string? FileNameCloudDistance;
        [XmlElement(ElementName = "FILE_NAME_QUALITY_L2_AEROSOL")]
        public string? FileNameQualityL2Aerosol;
        [XmlElement(ElementName = "FILE_NAME_QUALITY_L2_SURFACE_TEMPERATURE")]
        public string? FileNameQualityL2SurfaceTemperature;
        [XmlElement(ElementName = "FILE_NAME_QUALITY_L1_PIXEL")]
        public string? FileNameQualityL1Pixel;
        [XmlElement(ElementName = "FILE_NAME_QUALITY_L1_RADIOMETRIC_SATURATION")]
        public string? FileNameQualityL1RadiometricSaturation;
        [XmlElement(ElementName = "FILE_NAME_ANGLE_COEFFICIENT")]
        public string? FileNameAngleCoefficient;
        [XmlElement(ElementName = "FILE_NAME_METADATA_ODL")]
        public string? FileNameMetadataOdl;
        [XmlElement(ElementName = "FILE_NAME_METADATA_XML")]
        public string? FileNameMetadataXml;
        [XmlElement(ElementName = "DATA_TYPE_BAND_1")]
        public string? DataTypeBand1;
        [XmlElement(ElementName = "DATA_TYPE_BAND_2")]
        public string? DataTypeBand2;
        [XmlElement(ElementName = "DATA_TYPE_BAND_3")]
        public string? DataTypeBand3;
        [XmlElement(ElementName = "DATA_TYPE_BAND_4")]
        public string? DataTypeBand4;
        [XmlElement(ElementName = "DATA_TYPE_BAND_5")]
        public string? DataTypeBand5;
        [XmlElement(ElementName = "DATA_TYPE_BAND_6")]
        public string? DataTypeBand6;
        [XmlElement(ElementName = "DATA_TYPE_BAND_7")]
        public string? DataTypeBand7;
        [XmlElement(ElementName = "DATA_TYPE_BAND_ST_B10")]
        public string? DataTypeBandStB10;
        [XmlElement(ElementName = "DATA_TYPE_THERMAL_RADIANCE")]
        public string? DataTypeThermalRadiance;
        [XmlElement(ElementName = "DATA_TYPE_UPWELL_RADIANCE")]
        public string? DataTypeUpwellRadiance;
        [XmlElement(ElementName = "DATA_TYPE_DOWNWELL_RADIANCE")]
        public string? DataTypeDownwellRadiance;
        [XmlElement(ElementName = "DATA_TYPE_ATMOSPHERIC_TRANSMITTANCE")]
        public string? DataTypeAtmosphericTransmittance;
        [XmlElement(ElementName = "DATA_TYPE_EMISSIVITY")]
        public string? DataTypeEmissivity;
        [XmlElement(ElementName = "DATA_TYPE_EMISSIVITY_STDEV")]
        public string? DataTypeEmissivityStdev;
        [XmlElement(ElementName = "DATA_TYPE_CLOUD_DISTANCE")]
        public string? DataTypeCloudDistance;
        [XmlElement(ElementName = "DATA_TYPE_QUALITY_L2_AEROSOL")]
        public string? DataTypeQualityL2Aerosol;
        [XmlElement(ElementName = "DATA_TYPE_QUALITY_L2_SURFACE_TEMPERATURE")]
        public string? DataTypeQualityL2SurfaceTemperature;
        [XmlElement(ElementName = "DATA_TYPE_QUALITY_L1_PIXEL")]
        public string? DataTypeQualityL1Pixel;
        [XmlElement(ElementName = "DATA_TYPE_QUALITY_L1_RADIOMETRIC_SATURATION")]
        public string? DataTypeQualityL1RadiometricSaturation;
    }
}
